/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yoda
 */
package AppPackage;
        import java.util.Calendar;
        import java.util.GregorianCalendar;
public class NewJFrame extends javax.swing.JFrame {

        int timeRun = 0; 
        
        
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
       
                 
      initComponents();
                            
        new Thread ()
        {
            @Override
            public void run()
            {
                        while (timeRun == 0)
                        {
                        Calendar cal = new GregorianCalendar();
                                int hour = cal. get(Calendar.HOUR);
                                int min = cal. get(Calendar.MINUTE);
                                int sec = cal. get(Calendar.SECOND);
                                int AM_PM = cal. get(Calendar.AM_PM);
           
                                String day_night = "";
                                    if (AM_PM == 1)
                                    {
                                    day_night = "PM";
                                    }
                                        else
                                        {
                                        day_night = "AM";
                                        }
                                
                                String time = hour + ":" + min + ":" + sec + ":" + day_night;
                                
                                Clock.setText(time);       
                        }
            }
        }.start();



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Clock = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(750, 400));
        setPreferredSize(new java.awt.Dimension(750, 400));
        getContentPane().setLayout(null);

        Clock.setBackground(new java.awt.Color(51, 0, 0));
        Clock.setFont(new java.awt.Font("DS-Digital", 0, 74)); // NOI18N
        Clock.setForeground(new java.awt.Color(255, 255, 255));
        Clock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Clock.setText("7:45:50 PM");
        getContentPane().add(Clock);
        Clock.setBounds(120, 100, 510, 150);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Century Schoolbook L", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 153, 153));
        jButton1.setText("The WAKeY! Settings");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 240, 310, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("/home/pi/Desktop/GOD.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(750, 450));
        jLabel2.setMinimumSize(new java.awt.Dimension(750, 450));
        jLabel2.setPreferredSize(new java.awt.Dimension(750, 450));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 750, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        wake5 s = new wake5();
        s.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

   /* trystatic {
    File file = new File(“alarm.wav”);
    AudioInputStream audioIn = AudioSystem.getAudioInputStream(file);
    // Get a sound clip resource.
    Clip clip = AudioSystem.getClip();
    // Open audio clip and load samples from the audio input stream.
    clip.open(audioIn);
    clip.start();
    } catch (UnsupportedAudioFileException e) {
    e.printStackTrace();
    } catch (IOException e) {
    e.printStackTrace();
    } catch (LineUnavailableException e) {
    e.printStackTrace();
}*/
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Clock;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}